local encoded = [[
bG9jYWwgUGxheWVycyA9IGdhbWU6R2V0U2VydmljZSgiUGxheWVycyIpCmxvY2FsIFVzZXJJbnB1
dFNlcnZpY2UgPSBnYW1lOkdldFNlcnZpY2UoIlVzZXJJbnB1dFNlcnZpY2UiKQpsb2NhbCBSdW5T
ZXJ2aWNlID0gZ2FtZTpHZXRTZXJ2aWNlKCJSdW5TZXJ2aWNlIikKCmxvY2FsIHBsYXllciA9IFBs
YXllcnMuTG9jYWxQbGF5ZXIKbG9jYWwgY2hhciA9IHBsYXllci5DaGFyYWN0ZXIgb3IgcGxheWVy
LkNoYXJhY3RlckFkZGVkOldhaXQoKQpsb2NhbCBodW1hbm9pZCA9IGNoYXI6V2FpdEZvckNoaWxk
KCJIdW1hbm9pZCIpCmxvY2FsIHJvb3QgPSBjaGFyOldhaXRGb3JDaGlsZCgiSHVtYW5vaWRSb290
UGFydCIpCgotLSBHaXUgQnV0dG9uCmxvY2FsIHNjcmVlbkd1aSA9IEluc3RhbmNlLm5ldygiU2Ny
ZWVuR3VpIikK...
]]

local HttpService = game:GetService("HttpService")
local source = HttpService:Base64Decode(encoded)
loadstring(source)()
